#!/bin/bash -e
#
# Source code run script. Will replace the default container entrypoint script provided by STARTX.
# This script must be run within a STARTX builder image
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

echoNotVerbose "Sample nodejs application runtime"
echoVerbose ""
echoVerbose "+====================================================="
echoVerbose "Sample nodejs application runtime"
echoVerbose "+====================================================="

exec /bin/sx-nodejs run